export type SupportedLocationCountry = 'CL' | 'ES';

export const LOCATION_SUGGESTIONS: Record<
  SupportedLocationCountry,
  {
    cities: string[];
    regions: string[];
  }
> = {
  CL: {
    cities: [
      'Santiago',
      'Providencia',
      'Las Condes',
      'Nunoa',
      'La Florida',
      'Maipu',
      'Puente Alto',
      'Valparaiso',
      'Vina del Mar',
      'Concepcion',
      'Talcahuano',
      'Temuco',
      'Antofagasta',
      'La Serena',
      'Coquimbo',
      'Rancagua',
      'Talca',
      'Chillan',
      'Puerto Montt',
      'Osorno',
      'Punta Arenas',
      'Arica',
      'Iquique',
    ],
    regions: [
      'Metropolitana',
      'Valparaiso',
      'Biobio',
      'La Araucania',
      'Antofagasta',
      'Coquimbo',
      'O Higgins',
      'Maule',
      'Nuble',
      'Los Lagos',
      'Los Rios',
      'Magallanes',
      'Arica y Parinacota',
      'Tarapaca',
      'Atacama',
      'Aysen',
    ],
  },
  ES: {
    cities: [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Sevilla',
      'Zaragoza',
      'Malaga',
      'Murcia',
      'Palma',
      'Las Palmas',
      'Bilbao',
      'Alicante',
      'Cordoba',
      'Valladolid',
      'Vigo',
      'Gijon',
      'A Coruna',
      'Granada',
      'Tarragona',
      'Santa Cruz de Tenerife',
      'Pamplona',
    ],
    regions: [
      'Comunidad de Madrid',
      'Cataluna',
      'Comunidad Valenciana',
      'Andalucia',
      'Aragon',
      'Region de Murcia',
      'Islas Baleares',
      'Canarias',
      'Pais Vasco',
      'Castilla y Leon',
      'Galicia',
      'Asturias',
      'Navarra',
      'Cantabria',
      'Extremadura',
      'Castilla-La Mancha',
      'La Rioja',
    ],
  },
};
